(HOME, LANGUAGE, SCRIPT, LIST,
 TRANSLATION_JOB, TRANSLATION_CONFIRM,
 EDIT_TRANSLATION_TEXT, SAVE_EDITED_TRANSLATION,
 EDIT_SCRIPT_LIST, GET_EDITING_LANGUAGE, SAVE_EDITED_SCRIPT, DELETE_SCRIPT) = range(12)
END = -1
