# Generated by Django 4.0 on 2024-07-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ar', 'Arabic')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.FileField(upload_to='audios')),
            ],
        ),
    ]
