# Generated by Django 4.0 on 2024-07-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='script',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios'),
        ),
    ]
