# Generated by Django 4.0 on 2024-07-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_script_is_approved_alter_script_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='text_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
